# -*- coding: utf-8 -*-
"""DAAI Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C1tsuDgIDunX0p3hqjJqCePAn5sYsTva
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install wandb
!pip install loguru
!pip install pyrebase4
!pip install torcheval
!pip install torch torchvision torchaudio
!pip install git+https://github.com/facebookresearch/pytorchvideo.git

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/PoliTo/Project/error_recognition-main
import sys
sys.path.append('/content/drive/MyDrive/PoliTo/Project/error_recognition-main')

"""**Split** Step, V1, Omnivre"""

!python -m core.evaluate --variant MLP --backbone omnivore --ckpt /content/drive/MyDrive/PoliTo/Project/error_recognition-main/checkpoints/error_recognition_best/MLP/omnivore/error_recognition_MLP_omnivore_step_epoch_43.pt --task_name error_recognition --split step --threshold 0.6

"""Split Recordings, V1, Omnivre"""

!python -m core.evaluate --variant MLP --backbone omnivore --ckpt /content/drive/MyDrive/DAAI/error_recognition-main/checkpoints/error_recognition_best/MLP/omnivore/error_recognition_MLP_omnivore_recordings_epoch_33.pt --split recordings --threshold 0.4

"""Split Step, V2, Omnivre"""

!python -m core.evaluate --variant Transformer --backbone omnivore --ckpt /content/drive/MyDrive/DAAI/error_recognition-main/checkpoints/error_recognition_best/Transformer/omnivore/error_recognition_Transformer_omnivore_step_epoch_9.pt --split step --threshold 0.6

"""Split Recordings, V2, Omnivre"""

!python -m core.evaluate --variant Transformer --backbone omnivore --ckpt /content/drive/MyDrive/DAAI/error_recognition-main/checkpoints/error_recognition_best/Transformer/omnivore/error_recognition_Transformer_omnivore_recordings_epoch_31.pt --split recordings --threshold 0.4

"""Split Step V1 slowfast"""

!python -m core.evaluate --variant MLP --backbone slowfast --ckpt /content/drive/MyDrive/PoliTo/Project/error_recognition-main/checkpoints/error_recognition_best/MLP/slowfast/error_recognition_MLP_slowfast_step_best.pt --task_name error_recognition --split step --threshold 0.6

"""Split Recordings v1 slowfast"""

!python -m core.evaluate --variant MLP --backbone slowfast --ckpt /content/drive/MyDrive/PoliTo/Project/error_recognition-main/checkpoints/error_recognition_best/MLP/slowfast/error_recognition_MLP_slowfast_recordings_epoch_31.pt --task_name error_recognition --split recordings --threshold 0.4

"""Split Step V2 slowfast"""

!python -m core.evaluate --variant Transformer --backbone slowfast --ckpt /content/drive/MyDrive/PoliTo/Project/error_recognition-main/checkpoints/error_recognition_best/Transformer/slowfast/error_recognition_Transformer_slowfast_step_epoch_25.pt --task_name error_recognition --split step --threshold 0.6

"""Split Recordings V2 slowfast"""

!python -m core.evaluate --variant Transformer --backbone slowfast --ckpt /content/drive/MyDrive/PoliTo/Project/error_recognition-main/checkpoints/error_recognition_best/Transformer/slowfast/error_recognition_Transformer_slowfast_recordings_epoch_49.pt --task_name error_recognition --split recordings --threshold 0.4

"""ERROR CATEGORY RECOGNITION - STEP SPLITS"""

!python -m core.evaluate --variant MLP --backbone omnivore --ckpt /content/drive/MyDrive/PoliTo/Project/error_recognition-main/checkpoints/error_recognition_best/MLP/omnivore/error_recognition_MLP_omnivore_step_epoch_43.pt --split step --threshold 0.6 --task_name error_category_recognition --error_category 'Timing Error'

!python -m core.evaluate --variant MLP --backbone omnivore --ckpt /content/drive/MyDrive/PoliTo/Project/error_recognition-main/checkpoints/error_recognition_best/MLP/omnivore/error_recognition_MLP_omnivore_step_epoch_43.pt --split step --threshold 0.6 --task_name error_category_recognition --error_category 'Temperature Error'

!python -m core.evaluate --variant MLP --backbone omnivore --ckpt /content/drive/MyDrive/PoliTo/Project/error_recognition-main/checkpoints/error_recognition_best/MLP/omnivore/error_recognition_MLP_omnivore_step_epoch_43.pt --split step --threshold 0.6 --task_name error_category_recognition --error_category 'Preparation Error'

!python -m core.evaluate --variant MLP --backbone omnivore --ckpt /content/drive/MyDrive/PoliTo/Project/error_recognition-main/checkpoints/error_recognition_best/MLP/omnivore/error_recognition_MLP_omnivore_step_epoch_43.pt --split step --threshold 0.6 --task_name error_category_recognition --error_category 'Technique Error'

!python -m core.evaluate --variant MLP --backbone omnivore --ckpt /content/drive/MyDrive/PoliTo/Project/error_recognition-main/checkpoints/error_recognition_best/MLP/omnivore/error_recognition_MLP_omnivore_step_epoch_43.pt--split step --threshold 0.6 --task_name error_category_recognition --error_category 'Measurement Error'

"""ERROR CATEGORY RECOGNITION - RECORDING SPLITS"""

!python -m core.evaluate --variant MLP --backbone omnivore --ckpt /content/drive/MyDrive/PoliTo/Project/error_recognition-main/checkpoints/error_recognition_best/MLP/omnivore/error_recognition_MLP_omnivore_recordings_epoch_33.pt --split recordings --threshold 0.4 --task_name error_category_recognition --error_category 'Timing Error'

!python -m core.evaluate --variant MLP --backbone omnivore --ckpt /content/drive/MyDrive/PoliTo/Project/error_recognition-main/checkpoints/error_recognition_best/MLP/omnivore/error_recognition_MLP_omnivore_recordings_epoch_33.pt --split recordings --threshold 0.4 --task_name error_category_recognition --error_category 'Temperature Error'

!python -m core.evaluate --variant MLP --backbone omnivore --ckpt /content/drive/MyDrive/PoliTo/Project/error_recognition-main/checkpoints/error_recognition_best/MLP/omnivore/error_recognition_MLP_omnivore_recordings_epoch_33.pt --split recordings --threshold 0.4 --task_name error_category_recognition --error_category 'Preparation Error'

!python -m core.evaluate --variant MLP --backbone omnivore --ckpt /content/drive/MyDrive/PoliTo/Project/error_recognition-main/checkpoints/error_recognition_best/MLP/omnivore/error_recognition_MLP_omnivore_recordings_epoch_33.pt --split recordings --threshold 0.4 --task_name error_category_recognition --error_category 'Technique Error'

!python -m core.evaluate --variant MLP --backbone omnivore --ckpt /content/drive/MyDrive/PoliTo/Project/error_recognition-main/checkpoints/error_recognition_best/MLP/omnivore/error_recognition_MLP_omnivore_recordings_epoch_33.pt --split recordings --threshold 0.4 --task_name error_category_recognition --error_category 'Measurement Error'

"""Slowfast

Step splits
"""

!python -m core.evaluate --variant MLP --backbone slowfast --ckpt /content/drive/MyDrive/PoliTo/Project/error_recognition-main/checkpoints/error_recognition_best/MLP/slowfast/error_recognition_MLP_slowfast_step_best.pt --split step --threshold 0.6 --task_name error_category_recognition --error_category 'Timing Error'

!python -m core.evaluate --variant MLP --backbone slowfast --ckpt /content/drive/MyDrive/PoliTo/Project/error_recognition-main/checkpoints/error_recognition_best/MLP/slowfast/error_recognition_MLP_slowfast_step_best.pt --split step --threshold 0.6 --task_name error_category_recognition --error_category 'Temperature Error'

!python -m core.evaluate --variant MLP --backbone slowfast --ckpt /content/drive/MyDrive/PoliTo/Project/error_recognition-main/checkpoints/error_recognition_best/MLP/slowfast/error_recognition_MLP_slowfast_step_best.pt --split step --threshold 0.6 --task_name error_category_recognition --error_category 'Preparation Error'

!python -m core.evaluate --variant MLP --backbone slowfast --ckpt /content/drive/MyDrive/PoliTo/Project/error_recognition-main/checkpoints/error_recognition_best/MLP/slowfast/error_recognition_MLP_slowfast_step_best.pt --split step --threshold 0.6 --task_name error_category_recognition --error_category 'Technique Error'

!python -m core.evaluate --variant MLP --backbone slowfast --ckpt /content/drive/MyDrive/PoliTo/Project/error_recognition-main/checkpoints/error_recognition_best/MLP/slowfast/error_recognition_MLP_slowfast_step_best.pt --split step --threshold 0.6 --task_name error_category_recognition --error_category 'Measurement Error'

"""recordings split"""

!python -m core.evaluate --variant MLP --backbone slowfast --ckpt /content/drive/MyDrive/PoliTo/Project/error_recognition-main/checkpoints/error_recognition_best/MLP/slowfast/error_recognition_MLP_slowfast_recordings_epoch_31.pt --split recordings --threshold 0.4 --task_name error_category_recognition --error_category 'Timing Error'

!python -m core.evaluate --variant MLP --backbone slowfast --ckpt /content/drive/MyDrive/PoliTo/Project/error_recognition-main/checkpoints/error_recognition_best/MLP/slowfast/error_recognition_MLP_slowfast_recordings_epoch_31.pt --split recordings --threshold 0.4 --task_name error_category_recognition --error_category 'Temperature Error'

!python -m core.evaluate --variant MLP --backbone slowfast --ckpt /content/drive/MyDrive/PoliTo/Project/error_recognition-main/checkpoints/error_recognition_best/MLP/slowfast/error_recognition_MLP_slowfast_recordings_epoch_31.pt --split recordings --threshold 0.4 --task_name error_category_recognition --error_category 'Preparation Error'

!python -m core.evaluate --variant MLP --backbone slowfast --ckpt /content/drive/MyDrive/PoliTo/Project/error_recognition-main/checkpoints/error_recognition_best/MLP/slowfast/error_recognition_MLP_slowfast_recordings_epoch_31.pt --split recordings --threshold 0.4 --task_name error_category_recognition --error_category 'Technique Error'

!python -m core.evaluate --variant MLP --backbone slowfast --ckpt /content/drive/MyDrive/PoliTo/Project/error_recognition-main/checkpoints/error_recognition_best/MLP/slowfast/error_recognition_MLP_slowfast_recordings_epoch_31.pt --split recordings --threshold 0.4 --task_name error_category_recognition --error_category 'Measurement Error'

"""ERROR CATEGORY RECOGNITION V2

OMNIVRE

Step splits
"""

!python -m core.evaluate --variant Transformer --backbone omnivore --ckpt /content/drive/MyDrive/PoliTo/Project/error_recognition-main/checkpoints/error_recognition_best/Transformer/omnivore/error_recognition_Transformer_omnivore_step_epoch_9.pt --split step --threshold 0.6 --task_name error_category_recognition --error_category 'Timing Error'

!python -m core.evaluate --variant Transformer --backbone omnivore --ckpt /content/drive/MyDrive/PoliTo/Project/error_recognition-main/checkpoints/error_recognition_best/Transformer/omnivore/error_recognition_Transformer_omnivore_step_epoch_9.pt --split step --threshold 0.6 --task_name error_category_recognition --error_category 'Temperature Error'

!python -m core.evaluate --variant Transformer --backbone omnivore --ckpt /content/drive/MyDrive/PoliTo/Project/error_recognition-main/checkpoints/error_recognition_best/Transformer/omnivore/error_recognition_Transformer_omnivore_step_epoch_9.pt --split step --threshold 0.6 --task_name error_category_recognition --error_category 'Preparation Error'

!python -m core.evaluate --variant Transformer --backbone omnivore --ckpt /content/drive/MyDrive/PoliTo/Project/error_recognition-main/checkpoints/error_recognition_best/Transformer/omnivore/error_recognition_Transformer_omnivore_step_epoch_9.pt --split step --threshold 0.6 --task_name error_category_recognition --error_category 'Technique Error'

!python -m core.evaluate --variant Transformer --backbone omnivore --ckpt /content/drive/MyDrive/PoliTo/Project/error_recognition-main/checkpoints/error_recognition_best/Transformer/omnivore/error_recognition_Transformer_omnivore_step_epoch_9.pt --split step --threshold 0.6 --task_name error_category_recognition --error_category 'Measurement Error'

"""Recording Splits"""

!python -m core.evaluate --variant Transformer --backbone omnivore --ckpt /content/drive/MyDrive/PoliTo/Project/error_recognition-main/checkpoints/error_recognition_best/Transformer/omnivore/error_recognition_Transformer_omnivore_recordings_epoch_31.pt --split recordings --threshold 0.4 --task_name error_category_recognition --error_category 'Timing Error'

!python -m core.evaluate --variant Transformer --backbone omnivore --ckpt /content/drive/MyDrive/PoliTo/Project/error_recognition-main/checkpoints/error_recognition_best/Transformer/omnivore/error_recognition_Transformer_omnivore_recordings_epoch_31.pt --split recordings --threshold 0.4 --task_name error_category_recognition --error_category 'Temperature Error'

!python -m core.evaluate --variant Transformer --backbone omnivore --ckpt /content/drive/MyDrive/PoliTo/Project/error_recognition-main/checkpoints/error_recognition_best/Transformer/omnivore/error_recognition_Transformer_omnivore_recordings_epoch_31.pt --split recordings --threshold 0.4 --task_name error_category_recognition --error_category 'Preparation Error'

!python -m core.evaluate --variant Transformer --backbone omnivore --ckpt /content/drive/MyDrive/PoliTo/Project/error_recognition-main/checkpoints/error_recognition_best/Transformer/omnivore/error_recognition_Transformer_omnivore_recordings_epoch_31.pt --split recordings --threshold 0.4 --task_name error_category_recognition --error_category 'Technique Error'

!python -m core.evaluate --variant Transformer --backbone omnivore --ckpt /content/drive/MyDrive/PoliTo/Project/error_recognition-main/checkpoints/error_recognition_best/Transformer/omnivore/error_recognition_Transformer_omnivore_recordings_epoch_31.pt --split recordings --threshold 0.4 --task_name error_category_recognition --error_category 'Measurement Error'

"""SLOWFAST

Step slipts
"""

!python -m core.evaluate --variant Transformer --backbone slowfast --ckpt /content/drive/MyDrive/PoliTo/Project/error_recognition-main/checkpoints/error_recognition_best/Transformer/slowfast/error_recognition_Transformer_slowfast_step_epoch_25.pt --split step --threshold 0.6 --task_name error_category_recognition --error_category 'Timing Error'

!python -m core.evaluate --variant Transformer --backbone slowfast --ckpt /content/drive/MyDrive/PoliTo/Project/error_recognition-main/checkpoints/error_recognition_best/Transformer/slowfast/error_recognition_Transformer_slowfast_step_epoch_25.pt --split step --threshold 0.6 --task_name error_category_recognition --error_category 'Temperature Error'

!python -m core.evaluate --variant Transformer --backbone slowfast --ckpt /content/drive/MyDrive/PoliTo/Project/error_recognition-main/checkpoints/error_recognition_best/Transformer/slowfast/error_recognition_Transformer_slowfast_step_epoch_25.pt --split step --threshold 0.6 --task_name error_category_recognition --error_category 'Preparation Error'

!python -m core.evaluate --variant Transformer --backbone slowfast --ckpt /content/drive/MyDrive/PoliTo/Project/error_recognition-main/checkpoints/error_recognition_best/Transformer/slowfast/error_recognition_Transformer_slowfast_step_epoch_25.pt --split step --threshold 0.6 --task_name error_category_recognition --error_category 'Technique Error'

!python -m core.evaluate --variant Transformer --backbone slowfast --ckpt /content/drive/MyDrive/PoliTo/Project/error_recognition-main/checkpoints/error_recognition_best/Transformer/slowfast/error_recognition_Transformer_slowfast_step_epoch_25.pt --split step --threshold 0.6 --task_name error_category_recognition --error_category 'Measurement Error'

"""Recordings Split"""

!python -m core.evaluate --variant Transformer --backbone slowfast --ckpt /content/drive/MyDrive/PoliTo/Project/error_recognition-main/checkpoints/error_recognition_best/Transformer/slowfast/error_recognition_Transformer_slowfast_recordings_epoch_49.pt --split recordings --threshold 0.4 --task_name error_category_recognition --error_category 'Timing Error'

!python -m core.evaluate --variant Transformer --backbone slowfast --ckpt /content/drive/MyDrive/PoliTo/Project/error_recognition-main/checkpoints/error_recognition_best/Transformer/slowfast/error_recognition_Transformer_slowfast_recordings_epoch_49.pt --split recordings --threshold 0.4 --task_name error_category_recognition --error_category 'Temperature Error'

!python -m core.evaluate --variant Transformer --backbone slowfast --ckpt /content/drive/MyDrive/PoliTo/Project/error_recognition-main/checkpoints/error_recognition_best/Transformer/slowfast/error_recognition_Transformer_slowfast_recordings_epoch_49.pt --split recordings --threshold 0.4 --task_name error_category_recognition --error_category 'Preparation Error'

!python -m core.evaluate --variant Transformer --backbone slowfast --ckpt /content/drive/MyDrive/PoliTo/Project/error_recognition-main/checkpoints/error_recognition_best/Transformer/slowfast/error_recognition_Transformer_slowfast_recordings_epoch_49.pt --split recordings --threshold 0.4 --task_name error_category_recognition --error_category 'Technique Error'

!python -m core.evaluate --variant Transformer --backbone slowfast --ckpt /content/drive/MyDrive/PoliTo/Project/error_recognition-main/checkpoints/error_recognition_best/Transformer/slowfast/error_recognition_Transformer_slowfast_recordings_epoch_49.pt --split recordings --threshold 0.4 --task_name error_category_recognition --error_category 'Measurement Error'

"""**RNN**

Train: DON'T RUN AGAIN

Omnivre step
"""

!python -m train_er --variant RNN --backbone omnivore --split step --task_name error_recognition --num_epochs 50 --batch_size 512 --test-batch-size 512

"""Evaluate:"""

!python -m core.evaluate --variant RNN --backbone omnivore --ckpt /content/drive/MyDrive/PoliTo/Project/error_recognition-main/checkpoints/error_recognition_best/RNN/omnivre/error_recognition_step_omnivore_RNN_video_best.pt --split step --threshold 0.6 --task_name error_recognition

"""Omnivre Recordings"""

!python -m train_er --variant RNN --backbone omnivore --split recordings --task_name error_recognition --num_epochs 50 --batch_size 512 --test-batch-size 512

"""Evaluate"""

!python -m core.evaluate --variant RNN --backbone omnivore --ckpt /content/drive/MyDrive/PoliTo/Project/error_recognition-main/checkpoints/error_recognition_best/RNN/omnivre/error_recognition_recordings_omnivore_RNN_video_best.pt --split recordings --threshold 0.4 --task_name error_recognition

"""Slowfast step"""

!python -m train_er --variant RNN --backbone slowfast --split step --task_name error_recognition --num_epochs 50 --batch_size 512 --test-batch-size 512

!python -m core.evaluate --variant RNN --backbone slowfast --ckpt /content/drive/MyDrive/PoliTo/Project/error_recognition-main/checkpoints/error_recognition_best/RNN/slowfast/error_recognition_step_slowfast_RNN_video_best.pt --split step --threshold 0.6 --task_name error_recognition

"""Slowfast recordings"""

!python -m train_er --variant RNN --backbone slowfast --split recordings --task_name error_recognition --num_epochs 50 --batch_size 512 --test-batch-size 512

!python -m core.evaluate --variant RNN --backbone slowfast --ckpt /content/drive/MyDrive/PoliTo/Project/error_recognition-main/checkpoints/error_recognition_best/RNN/slowfast/error_recognition_recordings_slowfast_RNN_video_best.pt --split recordings --threshold 0.4 --task_name error_recognition

"""FEATURE EXTRACTOR

DON'T RUN AGAIN
"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/PoliTo/Project
import sys
sys.path.append('/content/drive/MyDrive/PoliTo/Project')

!python -m feature_extractors_main.segment_features.segment_feature_extractor --backbone perception_encoder

"""I don't know why, but it deleted the results, however, it's the extracted features that are on the folder already, don't run again

**Train** : DON'T RUN AGAIN
"""

!python -m train_er --variant MLP --backbone perception_encoder --split step --task_name error_recognition --num_epochs 50 --batch_size 512 --test-batch-size 512

"""Evaluate:"""

!python -m core.evaluate --variant MLP --backbone perception_encoder --ckpt /content/drive/MyDrive/PoliTo/Project/error_recognition-main/checkpoints/error_recognition_best/MLP/error_recognition_step_perception_encoder_MLP_video_best.pt --split step --threshold 0.6 --task_name error_recognition

"""Slpit Recordings"""

!python -m train_er --variant MLP --backbone perception_encoder --split recordings --task_name error_recognition --num_epochs 50 --batch_size 512 --test-batch-size 512

"""Evaluate"""

!python -m core.evaluate --variant MLP --backbone perception_encoder --ckpt /content/drive/MyDrive/PoliTo/Project/error_recognition-main/checkpoints/error_recognition_best/MLP/perception_encoder/error_recognition_recordings_perception_encoder_MLP_video_best.pt --split recordings --threshold 0.4 --task_name error_recognition